import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Literata } from "next/font/google";
import { Globe } from "lucide-react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const literata = Literata({
  variable: "--font-literata",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { LightboxProvider } from "@/context/LightboxContext";
import { Lightbox } from "@/components/ui/Lightbox";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${literata.variable}`}>
      <body suppressHydrationWarning>
        <LightboxProvider>
          {children}
          <Lightbox />
        </LightboxProvider>

        {/* Floating Language Toggler */}
        <LanguageSwitcher />

      </body>
    </html>
  );
}

