import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Literata } from "next/font/google";
import { Globe } from "lucide-react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const literata = Literata({
  variable: "--font-literata",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${literata.variable}`}>
      <body suppressHydrationWarning>
        {children}
        {/* Floating Language Toggler */}
        <div className="fixed bottom-24 right-6 z-[120] sm:bottom-6">
          <button className="flex items-center gap-2 rounded-full bg-black/10 backdrop-blur-md border border-black/5 px-4 py-2 text-sm font-medium text-page-text/90 shadow-lg transition-all hover:bg-black/20 hover:scale-105 font-montserrat">
            <Globe className="h-4 w-4 opacity-70" />
            <span>EN / ES</span>
          </button>
        </div>

      </body>
    </html>
  );
}

